version: '3.8'

services:

  web:
    build: .
    ports:
      - 8000:8000
    command: uvicorn src.main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A src.worker.celery worker --loglevel=info --logfile=src/logs/celery.log
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7

volumes:
  dev: {}
